[package]
name = "internet_detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"
ping = "0.4.0"
cancellation = "0.1.0"
ctrlc = "3.2.4"
